### ISSUE TITLE
astsam: look at this

### ISSUE THREAD

**Issue by kimocoder** [astsam/rtl8812au#118]
@astsam For 8822bu device and so (saw your fork), take a look at the unofficial RTW88(-USB) instead.

Made by kernel devs, Realtek and Neojou from Realtek. I just put them together, code for USB is now closed (private) but this is the future. mac80211 driver.

https://github.com/kimocoder/rtw88-usb

**Comment by astsam** [comment]
Very interesting, thank you!

**Comment by kimocoder** [comment]
Ur welcome sir 👍
