### ISSUE TITLE
How to increase TX power?

### ISSUE THREAD

**Issue by vverloop** [astsam/rtl8812au#15]
I have installed the driver for my AWUS036ACH, but TX power is not high. It only 12 dBm.
I have tried everything to increase the TX power.

What do you suggest? What is the right way?

**Comment by astsam** [comment]
1. Install v4.3.21 branch.
2. Attach adapter to USB 3.0 or externally powered USB 2.0 hub.
3. Use `$sudo iwconfig wlan0 txpower 30`

**Comment by vverloop** [comment]
Thanks! I will buy a external powered USB 3.0 hub or/and an USB 3.0 Micro Y-cable. And try again.

**Comment by kcdtv** [comment]
I also have the AWUS036ACH 
My laptop is weak and ti works perfectly on the USB 3.0 port with the original cable.
  Anyway: If you installed correctly the branch you should see 18dBm instead of 12dBm. 
   So before buying anything make sure that you installed correctly the branch for txpower.... 
cheers

**Comment by vverloop** [comment]
Thanks for thinking with us.
I thought also that is should not be needed to use external power...i will try it tomorrow and let you know.

I use the AWUS036ACH on Kali Linux & Vmware at my Mac Book Pro model late 2013 (with USB 3.0). I also discovered that i must also set in Vmware the usb setting from usb 2.0 to usb 3.0.  It is in the advanced settings section of USB in Vmware.

**Comment by vverloop** [comment]
Not working..Can anybody make a Youtube movie about this?

I should be simple, but i don't get it to work.

**Comment by vverloop** [comment]
https://bugs.kali.org/view.php?id=3260

**Comment by rujol** [comment]
Using this driver with 4.10.2-1-ARCH Linux and it is working, except increasing TxPower. Can this be done?

**Comment by astsam** [comment]
TX power control is implemented in the v4.3.21 branch.

**Comment by vverloop** [comment]
Not working @ kali?

**Comment by vverloop** [comment]
Also make the driver Master, so nobody make that mistake.

**Comment by adrianslabu** [comment]
I fixed my problem!
With version 5.1.5 i had only 12 dBm, txpower didn't work, low signal.
I installed 4.3.21 and its perfect !

1. apt-get remove realtek-rtl88xxau-dkms
2. reboot
3. git clone -b v4.3.21 https://github.com/aircrack-ng/rtl8812au.git
4. cd rtl8812au
5. make
6. make install

Enjoy!
