### ISSUE TITLE
V4.3.21 not effect

### ISSUE THREAD

**Issue by simepy** [astsam/rtl8812au#29]
Hello,

In ArchLinux 4.10.11
V4.3.21 don't work, I do:

`make`
`make install`
plug my Alfa
and
`sudo ip link set wlp0s20u3u3 down`
`sudo iw wlp0s20u3u3 set txpower 30`

And my Tx is always Tx-Power=12 dBm
Help please nothing change ?

Thanks

**Comment by astsam** [comment]
Clone and compile the v4.3.21 branch from this repo. You compiled some driver without tx power control.

**Comment by simepy** [comment]
Yes, I do
`git clone https://github.com/astsam/rtl8812au.git`
and `git branch v4.3.21`
`make`
`make install`
plug my Alfa
and
`sudo ip link set wlp0s20u3u3 down`
`sudo iw wlp0s20u3u3 set txpower 30`

And don't work, is my mistake ?

**Comment by astsam** [comment]
Use `sudo iw wlp0s20u3u3 set txpower fixed 3000` or `sudo iwconfig wlp0s20u3u3 txpower 30`.

**Comment by simepy** [comment]
OK it's work thanks
