### ISSUE TITLE
Compiling kernel error htc one m7cdwg

### ISSUE THREAD

**Issue by sviswas7** [astsam/rtl8812au#45]
Error with v4l2 driver video for linux during compiliation help pls

**Comment by Tikani** [comment]
Show logs and output please

**Comment by kcdtv** [comment]
And explain yourself a bit better too...
 

> Error with v4l2 driver video


What is the relation with WiFi drivers? This is very confusing.

**Comment by sviswas7** [comment]
i dont know whats the relation with wifi drivers but as the tutorial states i have enabled dvd frontends in the last step there i have seen that after compiling iam getting an error reguarding v4l2 i will post the log soon

**Comment by sviswas7** [comment]
thank you for replying iam recompiling the kernel as i found the fix my kernel doesnt support multimedia controller api (which iam enabling from the tutorial) disabling it crossed the error for v4l2....still compiling the kernel wii update for any other errors

**Comment by sviswas7** [comment]
i have successfully compiled the kernel :)

**Comment by Tikani** [comment]
This repository contains WiFi-drivery for the specific chipset only. Topic of your issue doesn't related with it at all. Please, close thread (anyway, your problem has been successfully resolved).
