### ISSUE TITLE
Unable to lock on channel in monitor mode (Alfa AC1200 - RTL8812AU)

### ISSUE THREAD

**Issue by pcamelo** [astsam/rtl8812au#52]
I'm unable to lock on a specific channel through the command line. I don't receive any error whatsoever.

Tried different combinations of channels but it sticks on Channel 1 with some random Channel variations according to wireshark.

**Branch:** v4.3.21

**Comment by astsam** [comment]
To switch channels the interface must be up, in the monitor mode and do not touched by the NetworkManager.

**Comment by pcamelo** [comment]
Did the first two, the last one may be the problem. Will try later.

**Comment by pcamelo** [comment]
Once I listed the interface in /etc/network/interfaces and restarted the NetworkManager it started to work.

Thank you very much!

**Comment by kimocoder** [comment]
Thanks for the notice sir
