### ISSUE TITLE
Error 2 "target 'modules' failed"

### ISSUE THREAD

**Issue by ClemPera** [astsam/rtl8812au#57]
Hello, i'm on Kali linux "4.6.0-kali1-amd64"

I have an error when i do "make", i've this error : 
```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.6.0-kali1-amd64/build M=/root/crack/pilote/4.3.21/rtl8812au  modules
make[1]: *** /lib/modules/4.6.0-kali1-amd64/build: No such file or directory.  Stop.
Makefile:1264: recipe for target 'modules' failed
make: *** [modules] Error 2
```
note : I've tested with "RTL8814=1" and with the 3 branch, it's the same result...

Thank you ! :+1:

**Comment by Tikani** [comment]
Do you have appropriate `linux-headers` installed?

**Comment by kimocoder** [comment]
Missing kernel headers as @Tikani has pointed out

**Comment by ClemPera** [comment]
Ok, I did not think about it thank's !
