### ISSUE TITLE
Bad return status for module build on kernel: 4.12.0-kali1-amd64 (x86_64)

### ISSUE THREAD

**Issue by ThePyrotechnic** [astsam/rtl8812au#65]
Attached here is the make.log
[make.txt](https://github.com/astsam/rtl8812au/files/1246936/make.txt)

**Comment by kimocoder** [comment]
No kernel v4.12 support here.
Use https://github.com/aircrack-ng/rtl8812au instead, an updated fork of astsam's

**Comment by ThePyrotechnic** [comment]
Thanks for the fast response, the driver is working as expected. This should probably be included with the latest version of Kali instead of the one I was pointed to, no?

**Comment by kimocoder** [comment]
No problem sir. It will be updated in repos soon I think, it's a fresh fork (from yesterday) that we've been working on to ensure the Kali support is maintained.

**Comment by ThePyrotechnic** [comment]
Gotcha! Thanks again for your help, and great work!
