### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by bekoleko** [astsam/rtl8812au#67]
root@kali:~/rtl8812au# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.12.0-kali1-amd64/build M=/root/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.12.0-kali1-amd64'
  CC [M]  /root/rtl8812au/os_dep/linux/ioctl_cfg80211.o
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_connect’:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:758:6: error: passing argument 2 of ‘cfg80211_roamed’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    , notify_channel
      ^~~~~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 from /root/rtl8812au/include/osdep_service.h:41,
                 from /root/rtl8812au/include/drv_types.h:32,
                 from /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.12.0-kali1-common/include/net/cfg80211.h:5435:6: note: expected ‘struct cfg80211_roam_info *’ but argument is of type ‘struct ieee80211_channel *’
 void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:760:6: warning: passing argument 3 of ‘cfg80211_roamed’ makes integer from pointer without a cast [-Wint-conversion]
    , cur_network->network.MacAddress
      ^~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 from /root/rtl8812au/include/osdep_service.h:41,
                 from /root/rtl8812au/include/drv_types.h:32,
                 from /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.12.0-kali1-common/include/net/cfg80211.h:5435:6: note: expected ‘gfp_t {aka unsigned int}’ but argument is of  type ‘unsigned char *’
 void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:756:3: error: too many arguments to function ‘cfg80211_roamed’
   cfg80211_roamed(padapter->pnetdev
   ^~~~~~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 from /root/rtl8812au/include/osdep_service.h:41,
                 from /root/rtl8812au/include/drv_types.h:32,
                 from /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.12.0-kali1-common/include/net/cfg80211.h:5435:6: note: declared here
 void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_add_monitor_if’:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:3639:10: error: ‘struct net_device’ has no member named ‘destructor’; did you mean ‘priv_destructor’?
  mon_ndev->destructor = rtw_ndev_destructor;
          ^~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_preinit_wiphy’:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6333:18: error: ‘WIPHY_FLAG_SUPPORTS_SCHED_SCAN’ undeclared (first use in this function)
  wiphy->flags |= WIPHY_FLAG_SUPPORTS_SCHED_SCAN;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6333:18: note: each undeclared identifier is reported only once for each function it appears in
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: At top level:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6366:25: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .change_virtual_intf = cfg80211_rtw_change_iface,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6366:25: note: (near initialization for ‘rtw_cfg80211_ops.change_virtual_intf’)
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6389:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .add_virtual_intf = cfg80211_rtw_add_virtual_intf,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:6389:22: note: (near initialization for ‘rtw_cfg80211_ops.add_virtual_intf’)
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.12.0-kali1-common/scripts/Makefile.build:307: recipe for target '/root/rtl8812au/os_dep/linux/ioctl_cfg80211.o' failed
make[4]: *** [/root/rtl8812au/os_dep/linux/ioctl_cfg80211.o] Error 1
/usr/src/linux-headers-4.12.0-kali1-common/Makefile:1532: recipe for target '_module_/root/rtl8812au' failed
make[3]: *** [_module_/root/rtl8812au] Error 2
Makefile:152: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.12.0-kali1-amd64'
Makefile:1855: recipe for target 'modules' failed
make: *** [modules] Error 2

I am using kali 2017.1 x64 on vmware 
Adapter: Alfa awus036ach
Why is this happening?

**Comment by kimocoder** [comment]
Kali now builds from [here](https://github.com/aircrack-ng/rtl8812au/tree/v5.1.5) as this repo still miss kernel v4.12 support. anyways, the "realtek-rtl88xxau-dkms" can be used using apt-get since the package got updated 43 hours ago supporting the v5.1.5 branch with several fixes. Credits still goes to astsam for the monitor/injection support, just to mention that.

**Comment by bekoleko** [comment]
Thanks!
