### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by mehmetgoksu** [astsam/rtl8812au#7]
before ı again install kali latest make and make install were working but today ı again fresh install and it gives me error
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-kali1-amd64/build M=/root/Desktop/rtl8812au-master  modules
make[1]: *** /lib/modules/4.9.0-kali1-amd64/build: No such file or directory.  Stop.
Makefile:1264: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by mehmetgoksu** [comment]
sudo apt-get install linux-headers-$(uname -r) build-essential   fixed my problem

**Comment by Gentech57** [comment]
mehmet bende hata veriyo knk            Paket listeleri okunuyor... Bitti
Bağımlılık ağacı oluşturuluyor       
Durum bilgisi okunuyor... Bitti      
E: linux-headers-4.6.0-kali1-amd64 paketi bulunamadı
E: 'linux-headers-4.6.0-kali1-amd64' ifadesine eşleşen herhangi bir paket bulunamadı
E: 'linux-headers-4.6.0-kali1-amd64' düzenli ifadesini içeren herhangi bir paket bulunamadı

**Comment by mehmetgoksu** [comment]
Live mi kullanıyorsun? Sources.list de kaynaklar düzgün gözüküyor mu?

**Comment by Gentech57** [comment]
knk sisteme yükledim hard disk de yani canlı canlı

**Comment by Gentech57** [comment]
sendekide awus036ac mi ?

**Comment by mehmetgoksu** [comment]
Sistemi kurarken network mirror kullanabildin mi

**Comment by mehmetgoksu** [comment]
Hayır ach

**Comment by Gentech57** [comment]
ag baglantısını diyorsan evet wifi üzerinden baglandım

**Comment by Gentech57** [comment]
monitör moduna geçiyormu peki seninki ? airmon-ng de ?

**Comment by mehmetgoksu** [comment]
Etc/apt/sources.list de yazanları buraya atar mısın

**Comment by Gentech57** [comment]
bash: Etc/apt/sources.list: Böyle bir dosya ya da dizin yok

**Comment by mehmetgoksu** [comment]
Nano /etc/apt/sources.list

**Comment by Gentech57** [comment]
dur kendim yerel olarak girdim atıyorum # 

# deb cdrom:[Debian GNU/Linux 2016.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160830-11:29]/ kali-rolling contrib main non-free

#deb cdrom:[Debian GNU/Linux 2016.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20160830-11:29]/ kali-rolling contrib main non-free

deb http://http.kali.org/kali kali-rolling main non-free contrib
# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

**Comment by Gentech57** [comment]
knk bu driver monitör modunu destekliyormu sende ?

**Comment by mehmetgoksu** [comment]
Destekliyor ama airmon ile başlatmayacaksın

**Comment by Gentech57** [comment]
bu iwconfig bildigime göre sadece wep şifrelemede işe yarıyor ? wpa da etkili olabilirmi veya başka bir altarnatif ?

**Comment by mehmetgoksu** [comment]
Derken?

**Comment by Gentech57** [comment]
sen monitör modunu ne için kullanıyorsun ?

**Comment by mehmetgoksu** [comment]
Driver i test amaçlı

**Comment by Gentech57** [comment]
tmm

**Comment by Gentech57** [comment]
sourceslist i attım sana ? şimdi ne yapmam gerekiyor

**Comment by mehmetgoksu** [comment]
Sıkıntısız gözüküyor

**Comment by Gentech57** [comment]
Mehmet birde sunu denesene https://github.com/Fredy72/rtl8821au. Airmon-ng kullan bir bak oluyormu diye

**Comment by Bluewild93** [comment]
Hi mehmetgoksu. Are u in kali linux?
I try to fix the same problem. but nothing happen. I can't do make. :/
