### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Gentech57** [astsam/rtl8812au#9]
root@kali:~/rtl8812au# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.6.0-kali1-amd64/build M=/root/rtl8812au  modules
make[1]: *** /lib/modules/4.6.0-kali1-amd64/build: Böyle bir dosya ya da dizin yok. Durdu.
Makefile:1264: recipe for target 'modules' failed
make: *** [modules] Error 2
root@kali:~/rtl8812au# 
root@kali:~/rtl8812au# uname -a
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by astsam** [comment]
1. Install kernel sources (headers).
2. Change to driver directory and run
`$ make KSRC=<path to kernel sources>`

**Comment by kcdtv** [comment]
Just to confirm that installation works without any problems in an updated and correctly configured Kali Linux thanks to  this commit: [https://github.com/astsam/rtl8812au/commit/bd960d186665cb5d611100a0152232ee584230d3](url)
![seleccion_180](https://cloud.githubusercontent.com/assets/7338484/22865056/8e301f64-f15c-11e6-92a3-b081249b9f84.png)
You're system is **not up to odate** (kernel 4.6) 
I suggest you to start by updating your system. 
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove && sudo reboot`
And you will see that everything goes fine

**Comment by ghost** [comment]
@astsam You saved my brain after 3 days of hardcore nervous breakdown. Thank you :)

**Comment by ressac** [comment]
I'm getting same error, running on latest kali live usb

```
root@kali:~/rtl8812au# uname -a
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux
root@kali:~/rtl8812au# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-kali3-amd64/build M=/root/rtl8812au  modules
make[1]: *** /lib/modules/4.9.0-kali3-amd64/build: No such file or directory.  Stop.
Makefile:1264: recipe for target 'modules' failed
make: *** [modules] Error 2
root@kali:~/rtl8812au# 

```
